### ISSUE TITLE
Add a Qwiic or STEMA connector

### ISSUE THREAD

**Issue by pacav69** [joeycastillo/LCD-FeatherWing#1]
I think you could add a add an option for a Qwiic or STEMA connector to the board this would add compatibility and flexibility to the Adafruit ecosystem and other boards such as the ESP32  series.
It could be just the pads so that a SMD could be soldered at a later time or be soldered in place as a purchase option.

Here is a link on the connectors
https://www.adafruit.com/product/4208
![image](https://user-images.githubusercontent.com/2259579/195222962-c97b8f67-07b9-4c9d-984c-e6822bb7f5fa.png)

**Comment by joeycastillo** [comment]
I think it's a great idea! Alas it might require a fairly extensive redesign; the reset button is occupying the spot on the board nearest to the I2C pins, so it would likely have to move to the opposite side to make room for a STEMMA-QT port there. 

I still have a lot of the current boards in stock, but if the time comes that I need to order and manufacture more, I will definitely consider this possibility. Thanks for the suggestion!
